### ISSUE TITLE
Unable to import the new permutation_test

### ISSUE THREAD

**Issue by sim-azan** [mdhaber/scipy#62]
hello, I recently upgraded to scipy 1.7.1 which is supposed to have the permutation_tests functionality but I am unable to import it. I followed the code here 

from scipy.stats import permutation_test

ImportError: cannot import name 'permutation_test' from 'scipy.stats' (C:\Anaconda3\envs\16Aug_test\lib\site-packages\scipy\stats\__init__.py)

https://34267-1460385-gh.circle-artifacts.com/0/html-scipyorg/reference/generated/scipy.stats.permutation_test.html#scipy.stats.permutation_test

Seems like the scipy version 1.7.1 does not have the permutation_test. So i am trying to install directly from your github repo. But there are a lot of dependencies errors (atlas, flame,openblas not found). Any way to go about installing your repo?

**Comment by mdhaber** [comment]
No other core developer has reviewed `permutation_test`, unfortunately, so the PR has not been merged and it is not intended to be in SciPy 1.7.1. I'm curious - what said that it is supposed to be in 1.7.1?

Please follow the instructions [here](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#development-environment) to set up a development environment. Then check out and build my branch.

I would appreciate it if you would leave a review at gh-13899 when you've had a chance to try it, or at least leave a note there expressing your interest. That would encourage other developers to review it so it can be merged and included in 1.8.0.

I'm the meantime, `ttest_ind` has a`permutations` option as of in 1.7.0, in case all you need is a permutation t-test.

**Comment by mdhaber** [comment]
@sim-azan - `permutation_test` has been available since the release of SciPy 1.8.0
