### ISSUE TITLE
JOSS Review Suggestions

### ISSUE THREAD

**Issue by acolum** [mdhaber/scipy#78]
Hi @mdhaber,

Nice work on this submission. I have a few small suggestions for improving your paper:

Under *Summary*:
1. Please change "in hope of" to "in **the** hope of."
2. Please change "Carefully designed tests" to "Carefully-designed tests."
3. Please rephrase' "p-hacking", producing' to ' "p-hacking" by producing' for greater clarity.

Under *Statement of need*:
1. Please change "cumulative density function (CDF)" to "cumulative **distribution** function (CDF)."
2. On line 37, "cumulative distribution function" could be replaced with "CDF."

Thanks,
Alyssa

For Reference: [Link to Review](https://github.com/openjournals/joss-reviews/issues/4383)

**Comment by mdhaber** [comment]
Thanks @acolum! I opened gh-79 so that the changes are easy to track.

**Comment by mdhaber** [comment]
Thanks again @acolum. It sounds like gh-79 addressed this, but if there were any remaining concerns, please let me know.

**Comment by acolum** [comment]
@mdhaber, thanks for making those changes! 

Unfortunately, I noticed that one instance of "CDF" remained in the paper.md file even after the pull request was merged.

**Comment by mdhaber** [comment]
Oops! Fixed in d6385bcef595eadfbef815b62fe53670199f7716. (Looks like my IDE also automatically added a newline at the end of the file, but I don't think that affected the way the file renders.)

**Comment by acolum** [comment]
Awesome, thanks! I'll continue my review back in the original JOSS issue.
